version: 1
disable_existing_loggers: False
formatters:
  request:
    (): pydatadeck.datasource.logging.RequestFormatter
    logFormat: '%(asctime)s [%(trace_id)s] %(levelname)-5s %(method)s %(path)s %(message)s'
  json:
    (): pydatadeck.datasource.logging.JsonFormatter
    service_name: api-gateway

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: request
  file:
    class: pydatadeck.datasource.logging.TraceLogTimedRotatingFileHandler
    level: INFO
    formatter: json
    filename: /data/datadeck/api-gateway/trace-%Y-%m-%d.json.log

root:
    level: INFO
    handlers: [console,file]

