"""empty message

Revision ID: 15e1b2b3bd95
Revises: 60fb2d30805b
Create Date: 2019-02-20 00:24:51.223421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e1b2b3bd95'
down_revision = '60fb2d30805b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_connection_table', sa.Column('dm_table_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_connection_table', 'dm_table_id')
    # ### end Alembic commands ###
