"""empty message

Revision ID: 2591f538e592
Revises: c1bc82d6bc5b
Create Date: 2019-01-10 21:14:57.901587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2591f538e592'
down_revision = 'c1bc82d6bc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_connection', sa.Column('name', sa.String(length=50), nullable=True))
    with op.batch_alter_table('business_connection') as batch_op:
        batch_op.drop_column('display_name')
        batch_op.drop_column('timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_connection', sa.Column('timezone', sa.VARCHAR(length=24), nullable=True))
    op.add_column('business_connection', sa.Column('display_name', sa.VARCHAR(length=50), nullable=True))
    with op.batch_alter_table('business_connection') as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###
