"""empty message

Revision ID: 262c6c69135e
Revises: d3df8f8b3512
Create Date: 2019-03-04 18:10:58.772754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '262c6c69135e'
down_revision = 'd3df8f8b3512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_calculated_field', sa.Column('function_contain', sa.Boolean(), nullable=True))
    op.add_column('business_calculated_field', sa.Column('group_function_contain', sa.Boolean(), nullable=True))
    op.add_column('business_calculated_field', sa.Column('type', sa.String(length=50), nullable=True))
    op.drop_column('business_calculated_field', 'data_type')
    op.drop_column('business_calculated_field', 'contain_group_function')
    op.drop_column('business_calculated_field', 'contain_function')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_calculated_field', sa.Column('contain_function', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('business_calculated_field', sa.Column('contain_group_function', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('business_calculated_field', sa.Column('data_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('business_calculated_field', 'type')
    op.drop_column('business_calculated_field', 'group_function_contain')
    op.drop_column('business_calculated_field', 'function_contain')
    # ### end Alembic commands ###
