"""empty message

Revision ID: 60fb2d30805b
Revises: fa148eff77a0
Create Date: 2019-01-30 15:25:15.313374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60fb2d30805b'
down_revision = 'fa148eff77a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_access_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('owner_id', sa.BIGINT(), nullable=False),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_access_rule_space_id'), 'business_access_rule', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_access_rule_space_id'), table_name='business_access_rule')
    op.drop_table('business_access_rule')
    # ### end Alembic commands ###
