"""empty message

Revision ID: 6b64bc05dc71
Revises: 5564b221b813
Create Date: 2019-04-01 17:44:00.401212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b64bc05dc71'
down_revision = '5564b221b813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_calculated_field', sa.Column('space_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_calculated_field', 'space_id')
    # ### end Alembic commands ###
