"""empty message

Revision ID: 70fc4a497980
Revises: 2591f538e592
Create Date: 2019-01-15 19:09:27.361461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70fc4a497980'
down_revision = '2591f538e592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_connection_dm_connection_id', table_name='business_connection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_business_connection_dm_connection_id', 'business_connection', ['dm_connection_id'], unique=True)
    # ### end Alembic commands ###
