"""empty message

Revision ID: bb0eb728327a
Revises: 15e1b2b3bd95
Create Date: 2019-03-01 16:58:03.049405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb0eb728327a'
down_revision = '6c14666b7722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_calculated_field',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('connection', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display', sa.String(length=120), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('candidates', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('allow_filter', sa.Boolean(), nullable=True),
    sa.Column('filter_ops', sa.Text(), nullable=True),
    sa.Column('allow_aggregation', sa.Boolean(), nullable=True),
    sa.Column('aggregation_ops', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection'], ['business_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_calculated_field')
    # ### end Alembic commands ###
