"""empty message

Revision ID: c1bc82d6bc5b
Revises: 
Create Date: 2019-01-10 12:02:14.508030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bc82d6bc5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_connection',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('ds_code', sa.String(length=24), nullable=True),
    sa.Column('timezone', sa.String(length=24), nullable=True),
    sa.Column('dm_connection_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_connection_dm_connection_id'), 'business_connection', ['dm_connection_id'], unique=True)
    op.create_index('user_space_index', 'business_connection', ['user_id', 'space_id'], unique=False)
    op.create_table('business_connection_file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['business_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_connection_sheet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['business_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_connection_table',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('connection_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['business_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_connection_filesheet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['business_connection_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_connection_filesheet')
    op.drop_table('business_connection_table')
    op.drop_table('business_connection_sheet')
    op.drop_table('business_connection_file')
    op.drop_index('user_space_index', table_name='business_connection')
    op.drop_index(op.f('ix_business_connection_dm_connection_id'), table_name='business_connection')
    op.drop_table('business_connection')
    # ### end Alembic commands ###
