"""empty message

Revision ID: d74c2dad7455
Revises: 262c6c69135e
Create Date: 2019-03-07 18:56:28.459757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd74c2dad7455'
down_revision = '262c6c69135e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('business_calculated_field', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('business_calculated_field', 'last_updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('business_calculated_field', 'last_updated_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('business_calculated_field', 'created_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
