"""empty message

Revision ID: fa148eff77a0
Revises: 2ddc42535bd1
Create Date: 2019-01-28 16:33:49.568738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa148eff77a0'
down_revision = '2ddc42535bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_segment', sa.Column('modifier_id', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_segment', 'modifier_id')
    # ### end Alembic commands ###
