"""empty message

Revision ID: 3abf4215c128
Revises: d81d90154a8b
Create Date: 2019-03-07 11:31:28.200713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3abf4215c128'
down_revision = 'd81d90154a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_manager_datasource', sa.Column('type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_manager_datasource', 'type')
    # ### end Alembic commands ###
