"""empty message

Revision ID: 74eea112c7b4
Revises: 2507af1b8eac
Create Date: 2019-01-16 12:19:58.296441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74eea112c7b4'
down_revision = '2507af1b8eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_manager_datasource', sa.Column('ds_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_manager_datasource', 'ds_id')
    # ### end Alembic commands ###
