"""empty message

Revision ID: d81d90154a8b
Revises: a9e27c2a8462
Create Date: 2019-02-27 11:44:09.844310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd81d90154a8b'
down_revision = 'a9e27c2a8462'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_manager_connection', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('data_manager_connection', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('data_manager_connection', 'last_updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'last_updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'published',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('data_manager_table', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('data_manager_table', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('data_manager_table', 'last_updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_manager_table', 'last_updated_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('data_manager_table', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('data_manager_table', 'created_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'published',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'last_updated_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('data_manager_datasource', 'created_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('data_manager_connection', 'last_updated_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('data_manager_connection', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('data_manager_connection', 'created_at',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
